# Generated by Django 4.2.3 on 2024-01-05 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_tags'),
        ('users', '0006_alter_user_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping_carts', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
