# Generated by Django 4.2.3 on 2023-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_init'), name='name_and_measure_uniq'),
        ),
    ]
