# Generated by Django 4.2.3 on 2023-10-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
